import { MantineProvider } from "@mantine/core";
import { ModalsProvider } from "@mantine/modals";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryClientContext from "./providers/QueryClientContext";
import SocketProvider from "./providers/SocketProvider";

import { emotionTransform, MantineEmotionProvider } from "@mantine/emotion";

import StatusBar from "&/StatusBar";
import "@mantine/core/styles.css";
import { cookies } from "next/headers";
import { RootStyleRegistry } from "./EmotionRootStyleRegistry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hlasovací systém MORS",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const c = await cookies();
  const token = await c.get("user_token")?.value;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootStyleRegistry>
          <MantineEmotionProvider>
            <MantineProvider stylesTransform={emotionTransform}>
              <QueryClientContext>
                <ModalsProvider
                  labels={{
                    cancel: "Zrušit",
                    confirm: "Ano",
                  }}
                >
                  <SocketProvider userToken={token || undefined}>
                    {children}
                    <StatusBar />
                  </SocketProvider>
                </ModalsProvider>
              </QueryClientContext>
            </MantineProvider>
          </MantineEmotionProvider>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
